name: Build and Deploy the site

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      # Checkout git branch
      - name: Checkout
        uses: actions/checkout@v3
      # Cache gems
      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      # Build the site and push new state to branch gh-pages
      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Run Test Scripts
        run: | 
          for f in *.sh; do \
            bash "$f" \
          done \
        working-directory: tests